#!/usr/bin/env python3
#
# Copyright (c) 2020 by Clemens Rabe <clemens.rabe@clemensrabe.de>
# All rights reserved.
# This file is part of gitcache (https://github.com/seeraven/gitcache)
# and is released under the "BSD 3-Clause License". Please see the LICENSE file
# that is included as part of this package.
#
"""Local cache for git repositories to speed up working with large repositories."""


# -----------------------------------------------------------------------------
# Module Import
# -----------------------------------------------------------------------------
from git_cache.cli import main_cli

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    main_cli()
