name: Unit and Functional Tests

permissions:
  contents: read

on:
  pull_request:

env:
  IN_GITHUB_ACTION: 1

# A list of available runners is available on
# https://docs.github.com/de/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-22.04-arm, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release make binutils
          sudo apt-get install -y python3-dev python3-venv
          sudo apt-get install git git-lfs
      - name: Check Style
        run: |
          make
      - name: Tests
        run: |
          make tests

  alpine:
    strategy:
      matrix:
        os: [alpine3.20]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lsb-release make binutils
          sudo apt-get install -y python3-dev python3-venv
          sudo apt-get install git git-lfs
      - name: Check Style
        run: |
          make check-style.venv.${{ matrix.os }}
      - name: Tests
        run: |
          make tests.venv.${{ matrix.os }}

  windows-2022:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      # Note: Keep python version in sync with pip-deps!
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y make
      - name: Refresh Environment
        shell: cmd
        run: |
          refreshenv
      - name: Check Style
        shell: cmd
        run: |
          C:\ProgramData\chocolatey\bin\make
      - name: Tests
        shell: cmd
        run: |
          C:\ProgramData\chocolatey\bin\make tests

  macos:
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: |
          brew install make
      - name: Check Style
        run: |
          make
      - name: Tests
        run: |
          make tests
